version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  # MongoAdmin kinda like phpmysql
  # DOCS: https://hub.docker.com/_/mongo-express
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"