version: '3'
services:
  # https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg
  nginx: 
    image: nginx:1.16
    container_name: production_nginx
    # Files you need to customize for nginx
    volumes:
      - ./server-config/nginx.conf:/etc/nginx/nginx.conf
      - ./server-config/hosts:/etc/hosts
      - ./server-config/letsencrypt/:/etc/letsencrypt/
      - ./server-config/sites-available/default:/etc/nginx/sites-available/default  
      - ./server-config/dhcpcd.conf:/etc/dhcpcd.conf
      # - ./server-config/interfaces:etc/network/interfaces
      # - certificates:/etc/letsencrypt/
    ports:
      - 3000:80
      # - 443:443
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  # # MongoAdmin kinda like phpmysql
  # # DOCS: https://hub.docker.com/_/mongo-express
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"

# volumes:
#   certificates: